apiVersion: configsync.example.com/v1alpha1
kind: ConfigMapPropagation
metadata:
  name: app-config-propagation
  namespace: config-sync-system
spec:
  # Input Configmap
  source:
    namespace: core-services
    name: app-config

  # Explicit per-namespace targets
  targets:
    - namespace: payments
      name: app-config
      createIfMissing: false # Defaults to true
    - namespace: billing
      name: app-config
      createIfMissing: true 

  # Namespace Selector
  namespaceSelector: {}       

  # Behavior controls
  propagationPolicy: Merge        # Merge | Overwrite
  syncMode: OnChange              # CreateOnce | OnChange | Periodic
  interval: 5m                    # used if Periodic or as a fallback
  globalCreateIfMissing: true     # create ConfigMaps in matched namespaces if missing
  allowSystemNamespaces: false    # must be explicit to touch kube-system, etc.
