apiVersion: configsync.example.com/v1alpha1
kind: ConfigMapPropagation
metadata:
  name: app-config-propagation
  namespace: config-sync-system
spec:
  # Input Configmap
  source:
    namespace: core-services
    name: app-config

  # Explicit per-namespace targets
  targets:
    - namespace: payments
      name: app-config
    - namespace: billing
      name: app-config

  # Namespace Selector
  namespaceSelector: {}       

  # Behavior controls
  propagationPolicy: Merge        # Merge | Overwrite
  deletionPolicy: Delete.         # Delete | Orphan
  syncMode: OnChange              # CreateOnce | OnChange | Periodic
  syncInterval: 5m                # used if Periodic or as a fallback
  createIfMissing: true           # create ConfigMaps in matched namespaces if missing
  allowSystemNamespaces: false
status:
  conditions:
    - type: Ready
      status: "False"
      reason: "OneOrMoreTargetsFailed"
      message: "See targetStatuses for details"
      lastTransitionTime: "2025-11-29T08:12:03Z"

  lastSyncedAt: "2025-11-29T08:12:03Z"
  observedGeneration: 3
  checksum: "sha256:aaa111..."

  targetsSummary:
    total: 25
    synced: 24
    failed: 1

  targetStatuses:
    - namespace: team-x
      name: app-config
      state: Error
      reason: PermissionDenied
      message: "User system:serviceaccount:... is forbidden"
      lastUpdated: "2025-11-29T08:12:03Z"

  