apiVersion: configsync.example.com/v1alpha1
kind: ConfigMapPropagation
metadata:
  name: app-config-propagation
  namespace: config-sync-system
spec:
  # Input Configmap
  source:
    namespace: core-services
    name: app-config

  # Explicit per-namespace targets
  targets:
    - namespace: payments
      name: app-config
    - namespace: billing
      name: app-config

  # Namespace Selector
  namespaceSelector: {}       

  # Behavior controls
  propagationPolicy: Merge        # Merge | Overwrite
  deletionPolicy: Delete.         # Delete | Orphan
  syncMode: OnChange              # CreateOnce | OnChange | Periodic
  syncInterval: 5m                # used if Periodic or as a fallback
  createIfMissing: true           # create ConfigMaps in matched namespaces if missing
  allowSystemNamespaces: false
status:
  